<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6RQWwtW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6RQWwtW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6RQWwtW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6RQWwtW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6RQWwtW\App_KernelDevDebugContainer([
    'container.build_hash' => '6RQWwtW',
    'container.build_id' => '45c92964',
    'container.build_time' => 1669130840,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6RQWwtW');
