<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSTxAbpr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSTxAbpr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSTxAbpr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSTxAbpr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSTxAbpr\App_KernelDevDebugContainer([
    'container.build_hash' => 'STxAbpr',
    'container.build_id' => '174532ff',
    'container.build_time' => 1668699473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSTxAbpr');
