<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSpfflzp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSpfflzp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSpfflzp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSpfflzp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSpfflzp\App_KernelDevDebugContainer([
    'container.build_hash' => 'Spfflzp',
    'container.build_id' => '9e3b3e71',
    'container.build_time' => 1669044927,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSpfflzp');
